name: ideal_exo
channels:
- conda-forge
dependencies:
- dask
- flake8
- ipykernel
- ipywidgets
- iris>=3.0
- matplotlib>=3.4
- numpy
- python=3.9
- pip
- python-stratify
- tqdm
- pip:
  - git+https://github.com/exoclim/aeolus.git
